format = """
[â•­â”€ $username$hostname â”€â”€ $time](bold green) 
[â•°â”€â¯ $directory](bold green) 
"""
[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '@[$hostname](bold yellow)'
trim_at = "."
disabled = false

[directory]
read_only = " ğŸ”’"
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

[time]
time_format = "%R"
style = "fg:#ff66cc"
format = 'at [$time]($style)'
disabled = false
